FROM python:3.6-slim-buster

RUN apt-get -y update && apt-get -y install curl vim

WORKDIR ./app

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY ./ ./

CMD ["python3", "app.py", "--develop"]
